apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
    tier: backend
spec:
  template:
    metadata:
      labels:
        app: app1
        tier: backend
    spec:
      containers:
      - name: app1
        image: deba153/bsapp1:latest
        ports:
        - containerPort: 5000
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh"]
      nodeSelector:
        app1-deploy: "true"
        
  replicas: 1
  selector:
    matchLabels:
      app: app1
      tier: backend
  