apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31080
  selector:
    app: nginx
    tier: backend